### ISSUE TITLE
Accidental experiment title cannot be expunged

### ISSUE THREAD

**Issue by agolo-alan-hogue** [ad-freiburg/elevant#12]
I ran a command as part of an attempt to debug another issue. It used the experiment name "test".

Now I have an experiment showing up in the UI named "test" that I cannot get rid of.

I have searched within all files in the repo for the word "test" and have deleted all of the files with "test" in the name. "test" still shows up in the web app.

I have deleted all the experiment files that I could find and re-run the commands with different names. An experiment with the name "test" is still there, and the new one with the new name cannot be found.

I have also changed the metadata file to have the correct name. 

How can I get rid of this error in the web app and successfully upload an experiment with the title I want it to have?

**Comment by agolo-alan-hogue** [comment]
After some time the UI seems to have updated on its own? Closing.

**Comment by flackbash** [comment]
In order to delete an experiment from the web app, you just need to delete the corresponding files in `evaluation-results/<linker_name>/<experiment_name>.<benchmark_name>.*`.
Then you need to reload the web app (and possibly disable caching, e.g. by opening the browser developer console, go to the network tab, set disable Cache to true and reload the tab).

**Comment by agolo-alan-hogue** [comment]
Thanks! Reloading the page wasn't working, nor was restarting the app, so I guess it was some kind of caching issue.
