### ISSUE TITLE
Article results not being displayed

### ISSUE THREAD

**Issue by agolo-alan-hogue** [ad-freiburg/elevant#16]
Hello,

I am trying to use a new benchmark and experiment over it. I ran all of the scripts as I have multiple times before and I don't think there were any errors. But when I upload the new benchmark and experiment, although it gives me what seem like plausible numbers, clicking on the experiment does not display the documents, instead spinning forever. 

In the console I can see that an error is happening while it is trying to read or format the first article. It happens at line 1814:

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'type')`

```
            if ("true_entity" in mention) {
                // Use the type of the parent entity because this is the type that counts in the evaluation.
                let curr_label_id = mention.true_entity.id;
                while (curr_label_id in child_label_to_parent) {
                    curr_label_id = child_label_to_parent[curr_label_id];
                }
                gt_annotation.gt_entity_type = label_id_to_label[curr_label_id].type;  <--- error
                // Get text of parent span
                if (curr_label_id !== mention.true_entity.id) {
                    let parent_span = label_id_to_label[curr_label_id].span;
                    const articles = (example_modal) ? window.articles_example_benchmark : window.benchmark_articles[benchmark];
                    gt_annotation.parent_text = articles[article_index].text.substring(parent_span[0], parent_span[1]);
                }
```

I added a try block and it looks like `label_id_to_label` is empty. The `mention` looks fine.

I have spent some time looking for any obvious problems in the datafiles and haven't found any.

If you would like to see it for yourself, you can do so here

Did something go wrong with the data generation, or is something wrong with the app? I would appreciate any assistance.

**Comment by flackbash** [comment]
Hi, I downloaded the files that correspond to this experiment from your ELEVANT instance (i.e. `Agolo-v3.benchmark.jsonl`, `agolo_01-10-2024.Agolo-v3.linked_articles.jsonl`, `agolo_01-10-2024.Agolo-v3.eval_cases.jsonl` and `agolo_01-10-2024.Agolo-v3.eval_results.json`) and added them to my local ELEVANT instance in order to inspect the problem further. However, I don't experience any problems at all with displaying the results in my web app.

Can you please check if you made any local changes to your evaluation-webapp (i.e. to [this](https://github.com/ad-freiburg/elevant/blob/master/evaluation-webapp/show_benchmark.js) `.js` file) that might cause this problem? Because the files seem to be fine.

**Comment by agolo-alan-hogue** [comment]
Ok, thanks, I guess I had not pulled a more recent version. It appears to work fine now. Thanks for your help!
