### ISSUE TITLE
make download_all: alias_to_qids.db: truncated gzip input

### ISSUE THREAD

**Issue by agolo-alan-hogue** [ad-freiburg/elevant#7]
I have gotten this error a few times in a row while trying to install without docker:

```
make download_all
wget https://ad-research.cs.uni-freiburg.de/data/entity-linking/wikidata_mappings.tar.gz
--2023-10-30 13:20:22--  https://ad-research.cs.uni-freiburg.de/data/entity-linking/wikidata_mappings.tar.gz
Resolving ad-research.cs.uni-freiburg.de (ad-research.cs.uni-freiburg.de)... 132.230.150.101
Connecting to ad-research.cs.uni-freiburg.de (ad-research.cs.uni-freiburg.de)|132.230.150.101|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10473195010 (9.8G) [application/x-gzip]
Saving to: ‘wikidata_mappings.tar.gz.2’

wikidata_mappings.tar.gz.2                    100%[==============================================================================================>]   9.75G  16.7MB/s    in 10m 2s  

2023-10-30 13:30:25 (16.6 MB/s) - ‘wikidata_mappings.tar.gz.2’ saved [10473195010/10473195010]

tar -xvzf wikidata_mappings.tar.gz -C ./data/wikidata_mappings/
x alias_to_qids.db: truncated gzip input
tar: Error exit delayed from previous errors.
make: *** [download_wikidata_mappings] Error 1

```

**Comment by agolo-alan-hogue** [comment]
I was able to get this working by downloading the files in Chrome and opening them in MacOS finder. I then copied them to the data directory. I am not sure why this happened -- perhaps something to do with differences in MacOS command line tools?

**Comment by flackbash** [comment]
I just tested the Makefile target and had no problems under Linux.

One thing I noticed in your log: the downloaded file is saved to `wikidata_mappings.tar.gz.2`, instead of `wikidata_mappings.tar.gz`. The latter probably already exists from a previous incomplete run of the Makefile target.
The Makefile command however will still try to extract the file `wikidata_mappings.tar.gz`. If you remove that existing file and try to run the target again, do you still get the same error?

If so, then my best guess it that it's connected to your OS, even though the error message seems to say that there's something wrong with the downloaded file.
ELEVANT is set up for Linux and not tested at all under MacOS. I recommend running it using Docker. If you experience any more issues with the Docker Setup, please let me know.
